### ISSUE TITLE
Error when i want see likes count

### ISSUE THREAD

**Issue by qmeyti** [mohamednagy/Laravel-rating#10]
when i want see likes count gave this message:

BadMethodCallException
Call to undefined method App\User::ratings()

**Comment by mohamednagy** [comment]
@see https://github.com/mohamednagy/Laravel-rating#rating
to rate a model use 
`$user->rate($postModel, 5);`
to get the average ratings use: 
`$post->ratingsAvg();`
to get the total ratings count use: 
`$post->ratingsCount();`
