### ISSUE TITLE
Can you add support for Laravel7

### ISSUE THREAD

**Issue by tarangpatel61** [mohamednagy/Laravel-rating#11]

**Comment by ichtrojan** [comment]
#12

**Comment by tarangpatel61** [comment]
i can not call $user->ratings() method it gives 

![Screen Shot 2020-04-02 at 4 20 41 pm](https://user-images.githubusercontent.com/35031138/78214968-fc7fc000-74fd-11ea-93db-7214d842b5c0.png)
