### ISSUE TITLE
Base table or view not found: 1146 Table 'rating.ratings' doesn't exist (SQL: alter table `ratings` add `type` varchar(255) null)

### ISSUE THREAD

**Issue by malijani** [mohamednagy/Laravel-rating#27]
Hi, thanks for maintaining this good package! after running `php artisan migrate` I got this error : 

> Migrating: 2021_04_20_143520_add_type_column_to_ratings_table
> 
>    Illuminate\Database\QueryException 
> 
>   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'rating.ratings' doesn't exist (SQL: alter table `ratings` add `type` varchar(255) null)
> 
>   at vendor/laravel/framework/src/Illuminate/Database/Connection.php:678
>     674▕         // If an exception occurs when attempting to run a query, we'll format the error
>     675▕         // message to include the bindings with SQL, which will make this exception a
>     676▕         // lot more helpful to the developer instead of just the database's errors.
>     677▕         catch (Exception $e) {
>   ➜ 678▕             throw new QueryException(
>     679▕                 $query, $this->prepareBindings($bindings), $e
>     680▕             );
>     681▕         }
>     682▕ 
> 
>   • A table was not found: You might have forgotten to run your migrations. You can run your migrations using `php artisan migrate`. 
>     https://laravel.com/docs/master/migrations#running-migrations
> 
>       +9 vendor frames 
>   10  database/migrations/2021_04_20_143520_add_type_column_to_ratings_table.php:13
>       Illuminate\Support\Facades\Facade::__callStatic()
> 
>       +21 vendor frames 
>   32  artisan:37
>       Illuminate\Foundation\Console\Kernel::handle()

The problem is : **LaravelRatingServiceProvider.php** 
we got this : 
```
__DIR__.'/../database/migrations/create_ratings_table.php' => app()->basePath().'/database/migrations/'.date('Y_m_d_His').'_create_ratings_table.php',
__DIR__.'/../database/migrations/add_type_column_to_ratings_table.php' => app()->basePath().'/database/migrations/'.date('Y_m_d_His').'_add_type_column_to_ratings_table.php',
```
generating migration prefixes in the same time! so **add_type_column_to_ratings_table.php** migrates **before** **create_ratings_table.php** 

The solution is : **merging migrations in one file** 

```
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateLaravelRatingTable extends Migration
{
    public function up()
    {
        Schema::create('ratings', function (Blueprint $table) {
            $table->bigIncrements('id');

            $table->string('type')->nullable();
            $table->morphs('model');
            $table->morphs('rateable');
            $table->decimal('value', 2, 1);

            $table->timestamps();
        });
    }

    public function down()
    {
        Schema::dropIfExists('ratings');
    }

}

```

**Comment by nagi1** [comment]
Fixed in v2.2
