### ISSUE TITLE
Cannot declare class CreateLaravelRatingTable, because the name is already in use

### ISSUE THREAD

**Issue by malijani** [mohamednagy/Laravel-rating#28]
After #27 ; and solving the problem when i run `php artisan migrate` I've got this error:

> Symfony\Component\ErrorHandler\Error\FatalError 
> 
>   Cannot declare class CreateLaravelRatingTable, because the name is already in use
> 
>   at database/migrations/2021_04_21_015322_create_ratings_table.php:7
>       3▕ use Illuminate\Database\Migrations\Migration;
>       4▕ use Illuminate\Database\Schema\Blueprint;
>       5▕ use Illuminate\Support\Facades\Schema;
>       6▕ 
>   ➜   7▕ class CreateLaravelRatingTable extends Migration
>       8▕ {
>       9▕     public function up()
>      10▕     {
>      11▕         Schema::create('ratings', function (Blueprint $table) {
> 
> 
>    Whoops\Exception\ErrorException 
> 
>   Cannot declare class CreateLaravelRatingTable, because the name is already in use
> 
>   at database/migrations/2021_04_21_015322_create_ratings_table.php:7
>       3▕ use Illuminate\Database\Migrations\Migration;
>       4▕ use Illuminate\Database\Schema\Blueprint;
>       5▕ use Illuminate\Support\Facades\Schema;
>       6▕ 
>   ➜   7▕ class CreateLaravelRatingTable extends Migration
>       8▕ {
>       9▕     public function up()
>      10▕     {
>      11▕         Schema::create('ratings', function (Blueprint $table) {
> 
>       +1 vendor frames 
>   2   [internal]:0
>       Whoops\Run::handleShutdown()

The problem is : **CreateLaravelRatingTable** class name for **create_ratings_table** migration!

The solution is : change migration class name to **CreateRatingsTable**

**Comment by nagi1** [comment]
Fixed in v2.2
