### ISSUE TITLE
Not compatible with morph maps

### ISSUE THREAD

**Issue by SaphiLC** [mohamednagy/Laravel-rating#3]
I have morph maps in my app, and when i rate something, they get ignored so the relations doesnt work and i cant get rating data.... lost hours trying to figure this out... im pretty new to laravel so not sure if im doing something wrong or is this package that is just ignoring the morph maps data, ill have to disable them for now ..........

**Comment by mohamednagy** [comment]
@SaphiLC i added a support for `morphMaps` you can use `v1.1` thanks for reporting the issue
