### ISSUE TITLE
Traits not recognized

### ISSUE THREAD

**Issue by cybercrowd** [mohamednagy/Laravel-rating#5]
Still getting errors for uses of the traits after successfully install ServiceProvider files and update composer.
- Method Illuminate\Database\Eloquent\Collection::upVoted does not exist
- Method Illuminate\Database\Eloquent\Collection::liked does not exist

PHP 7.1
Laravel Framework 5.6.39

```
use Nagy\LaravelRating\Traits\Rate\CanRate;
use Nagy\LaravelRating\Traits\Vote\CanVote;
use Nagy\LaravelRating\Traits\Like\CanLike;
class Users extends Authenticatable
{
    use CanRate;
    use CanVote;
    use CanLike;
...
}
use Nagy\LaravelRating\Traits\Like\Likeable;
class Articles extends Model
{
    use Likeable;
...
}
```

**Controller:**
```
$user = Users::where('id', auth()->user()->id)->get();
$user->liked($article);  
```
_**Error:** Method Illuminate\Database\Eloquent\Collection::liked does not exist_

**Comment by mohamednagy** [comment]
`get` returns a collection not `User` model try to use it like that
```
$user  = User::find(auth()->user()->id);
$user->liked($article);
```
or simply you can do that ;)
```
auth()->user()->liked($article);
```

**Comment by cybercrowd** [comment]
I was using user->liked() and was wondering why there wasn't anything in the database when it should have been user->like() to store a record. I need to pay attention to my verbs vs adjectives and nouns. :-)
