### ISSUE TITLE
Feature request: Remove rating

### ISSUE THREAD

**Issue by rtrudel** [mohamednagy/Laravel-rating#8]
It would be useful to allow a user to remove their rating by sending `null`, `false` or `-1` in along the `rate()` method. This should delete the corresponding row in DB or at least adapt the count and average by ignoring zero ratings.

ex:
```php
$user->rate($model, null);
```
or by adding a new method:

ex:
```php
$user->unrate($model);
```
In most UI, it's possible to remove the stars, but as now, it's only possible to zero rate, distorting average. 

Thank you in advance!

**Comment by nagi1** [comment]
Hey, thanks for taking the time to write this issue, this seems like a valid request and i'm working on enhancing this package. 

A PR for this would be more than welcome.

Thanks.

**Comment by nagi1** [comment]
Added on v2.0 :smile:
